apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-ietf-at"
  labels:
    app: ietf-at
spec:
  replicas: {{ .Values.ReplicaCount }}
  selector:
    matchLabels:
      app: ietf-at
  template:
    metadata:
      labels:
        app: ietf-at
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

